# -I tells the compiler where to look for cmo files
core := `ocamlfind query core`
re := `ocamlfind query re`
default:
	ocamlc -g -I lib -c lib/advent.mli
	ocamlfind ocamlc -g -package core,stdio, -I lib -c lib/advent.ml
	ocamlfind ocamlc -g -package core -I lib -c src/day4.ml
	# Linking stage 
	ocamlfind ocamlc -g -package core,stdio -linkpkg -o build/day4 lib/advent.cmo src/day4.cmo
	build/day4
	
debug:
	ocamldebug build/day4
	
toplevel:
	ocamlfind ocamlmktop -package core,stdio -linkpkg -o build/toplevel lib/advent.cmo src/day4.cmo
	build/toplevel
utop:
	#utop -I lib -I {{core}} src/day4.cmo
	echo {{core}}
	utop -I {{core}} src/test.cmo
	
test:
	ocamlfind ocamlc -package core -c src/test.ml
	ocamlfind ocamlc -package core -linkpkg -o build/test src/test.cmo
	build/test


